### ISSUE TITLE
Error while retrieving metadata of .txt, .bmp files

### ISSUE THREAD

**Issue by riteshpd** [RoyalBingBong/exiftool-wrapper#1]
Utility returns error 
1) for all .txt, .bmp files.
2) All Empty (0 byte) size files of any extension.
3) When passed a directory, and if there is an issue with one file, error is thrown.

.docx, .xslx etc files work without any issues.

Platform: Windows

Example:

PS C:\ClientApps\Study\exiftooljsondb> node .\index.js
error found
{ Error: Exiftool returned an error
    at ChildProcess.exif.on.code (C:\ClientApps\Study\exiftooljsondb\node_modules\exiftool-wrapper\lib\exiftool-wrapper.js:80:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  commandlog:
   { stdout:
      '[{\r\n  "SourceFile": "test1/abc.txt",\r\n  "FileSize": "3.3 kB"\r\n}]\r\n',
     stderr: '' } }

**Comment by RoyalBingBong** [comment]
Could confirm everything except `.bmp` files, empty files throw an error, but normal ones are fine. The errors are due to exiftool returning code 1 for empty files and unknown file types (txt). The metadata is fine, but there is an additional property `Error`the error message, i.e. 'File is empty' or 'Unknown file type'.

I also need to catch when a directory has no images in it, then the output will be
